export default {
  version: 2,
  query: 'javascript',
  location: 'austin, tx',
  dupefilter: true,
  highlight: false,
  radius: 25,
  start: 1,
  end: 10,
  totalResults: 547,
  pageNumber: 0,
  results: [
    {
      jobtitle: 'JavaScript Developer 1',
      company: 'XYZ Corp., 1',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.1,
      longitude: -97.1,
      jobkey: 'dsah4387y293rijds98a734',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 2',
      company: 'XYZ Corp., 2',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 03 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.2,
      longitude: -97.2,
      jobkey: 'dsakjhdf7843',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '12 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 3',
      company: 'XYZ Corp., 3',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 04 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.3,
      longitude: -97.3,
      jobkey: 'dsjkh7843jkfgv8342',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 4',
      company: 'XYZ Corp., 4',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 05 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.4,
      longitude: -97.4,
      jobkey: 'dskajjhsdf843987yf',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 5',
      company: 'XYZ Corp. 5,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 06 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.5,
      longitude: -97.5,
      jobkey: 'jkds89043rtkjjhsd0',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 6',
      company: 'XYZ Corp., 6',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 07 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented <b>JavaScript</b> Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.6,
      longitude: -97.6,
      jobkey: 'jklsdfa943r3',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
  ],
};
