export default {
  version: 2,
  query: 'javascript',
  location: 'austin, tx',
  dupefilter: true,
  highlight: false,
  radius: 25,
  start: 1,
  end: 10,
  totalResults: 547,
  pageNumber: 0,
  results: [
    {
      jobtitle: 'JavaScript Developer 1',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 2',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 3',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 4',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 5',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
    {
      jobtitle: 'JavaScript Developer 6',
      company: 'XYZ Corp.,',
      city: 'Austin',
      state: 'TX',
      country: 'US',
      formattedLocation: 'Austin, TX',
      source: 'Dice',
      date: 'Mon, 02 Aug 2017 16:21:00 GMT',
      snippet: `looking for an object-oriented Java Developer... JavaScript,
            HTML JavaScript, AJAX, Angular, React, Vue) desirable. Familiarity with
            Node ...`,
      url: 'http://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203',
      onmousedown: 'indeed_clk(this, "0000");',
      latitude: 30.27127,
      longitude: -97.74103,
      jobkey: '12345',
      sponsored: false,
      expired: false,
      indeedApply: true,
      formattedLocationFull: 'Austin, TX',
      formattedRelativeTime: '11 hours ago',
    },
  ],
};
